### ISSUE TITLE
Next button won't scroll to end in Horizontal Overflow if width is changed by CSS

### ISSUE THREAD

**Issue by hchokshi** [Microsoft/fast-dna#1378]
**Describe the bug; what happened?**
When creating a horizontal overflow with flex previous/next buttons on either side of the control, the next button will not scroll to the end (`OverflowChange.overflowEnd=false` event). It will scroll almost to the end, the event can be fired via using mouse/keyboard scrolling to scroll another pixel further.

**What are the steps to reproduce the issue?**
```jsx
<HorizontalOverflow onOverflowChange={this.handleOverflowChange} managedClasses={{
    horizontalOverflow: 'horizontalOverflow',
    horizontalOverflow_previous: 'horizontalOverflow_previous',
    horizontalOverflow_next: 'horizontalOverflow_next',
}}>
    <Button slot='previous' disabled={this.state.isAtStart}>&lt;</Button>
    {this.props.items.map(itemToCard)}
    {/* Have also tried putting previous button here, instead */}
    <Button slot='next' disabled={this.state.isAtEnd}>&gt;</Button>
</HorizontalOverflow>
```

```js
handleOverflowChange = (e) => {
    // Disable buttons when they can't scroll any further
    this.setState({
        isAtStart: !e.overflowStart,
        isAtEnd: !e.overflowEnd,
    });
};
```

```css
.horizontalOverflow {
  width: 50vw;
  max-width: 50rem;
  display: flex;
}

.horizontalOverflow .horizontalOverflow_previous {
  order: -1; /* move previous button to before overflow */
  display: flex;
  flex-direction: column;
  justify-content: center;
  margin-right: 1rem;
}

.horizontalOverflow .horizontalOverflow_next {
  display: flex;
  flex-direction: column;
  justify-content: center;
  margin-left: 1rem;
}
```

1. Scroll to the end using next button
2. Press it another 10-15 times and it won't scroll further, but is not disabled having "reached the end"
3. Scroll a little bit further to the end direction (e.g. using `Shift+Scroll` or keyboard)
4. Next button now disabled, having reached actual end

**What behavior did you expect?**
Next button scrolls to the very end, and becomes disabled. I believe the behaviour may be caused by the width of the scroll container changing due to the previous/next buttons being moved inline via flex. If the above CSS is removed, making the buttons appear below the scroll container, the behaviour works as expected.

**If applicable, provide screenshots:**
After clicking `>` button to come to item 4
![image](https://user-images.githubusercontent.com/10136407/52737627-a3fc0500-2f81-11e9-9d9d-4882ca9e2025.png)

After scrolling the tiniest bit further using `Shift+Scroll` (note disabled `>` button)
![image](https://user-images.githubusercontent.com/10136407/52737646-b4ac7b00-2f81-11e9-9086-c172a1f00eaf.png)

**In what environment did you see the issue?**

* OS & Device: Windows 10 Enterprise 1809
* Browser
    - Chrome 72.0.3626.81 (Official Build) (64-bit)
    - Edge 44.17763.1.0

* Version [e.g. 1.8.0]: `fast-components-react-base v3.7.0`

**Is there any additional context?**
**Working as expected** in Firefox Developer Edition 66.0b7 (64-bit)
